version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo Installing dependencies...
      - apt-get update -y
      - apt-get install -y unzip
     
      

  build:
    commands:
      - echo Downloading the .zip file from S3...
      - mkdir sankhanew
      - cd sankhanew
      - echo "Hi I'm Sankha" > test.txt
      #- unlink p8-deployments
      - aws s3 cp s3://test-pack-s3-123456/p8-deployments-carbonplace-4.0.0.tar.gz .
      - echo Unzipping the file...
      - tar -xvf p8-deployments-carbonplace-4.0.0.tar.gz
      - mv p8-deployments p8-deployments-carbonplace-4.0.0
      #- cd /home/ubuntu/p8
      - sudo ln -s /home/ubuntu/p8/p8-deployments-carbonplace-4.0.0 p8-deployments
      #- mv p8-deployments p8-deployments-3.3.0
      #- ln -s /home/ubuntu/p8/p8-deployments-carbonplace-3.3.0 p8-deployments
      - export P8_IM_SCRIPT_PATH=p8/p8-deployments/scripts
      #- cd ~/p8/p8-deployments/profiles
      #- ./configure.sh -pvp carbon -pip production -uip yaalaprod apply


      

artifacts:
  files:
    - '**/*'
