version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo Installing dependencies...
      - apt-get update -y
      - apt-get install -y unzip
     
      

  build:
    commands:
      - echo Downloading the .zip file from S3...
      - unlink p8-deployments
      - aws s3 cp s3://test-pack-s3-123456/p8-deployments-carbonplace-3.3.0.zip .
      - echo Unzipping the file...
      - unzip p8-deployments-carbonplace-3.3.0.zip
      - ln -s /home/ubuntu/p8/p8-deployments-carbonplace-3.3.0 p8-deployments
      - mv p8-deployments p8-deployments-3.3.0

artifacts:
  files:
    - '**/*'
